### ISSUE TITLE
Mechanical Fryer outputs 2 items instead of one

### ISSUE THREAD

**Issue by Blizzor** [pyzpre/Create-Bicycles-Bitterballen#1]
The Mechanical Fryer ouputs 2 items.
This happens, when the fryer contains more than one item.

**Comment by pyzpre** [comment]
Hi! this is intended behavior, it doesn't create extra items out of thin air, it just processes 2 at a time to speed up the frying process :) 

unless you mean something else?

**Comment by Blizzor** [comment]
I forgot to add the important part...
the fluid is consumed, as it was one item, so it only takes half of the fluid it should take

**Comment by pyzpre** [comment]
oh wow yeah you're right, I'll get onto that asap

**Comment by pyzpre** [comment]
good news, we have a fix in place, and will be shipped with next update :D
