### ISSUE TITLE
Crash when Mob receives the Oiled Up effect

### ISSUE THREAD

**Issue by Mickeon** [pyzpre/Create-Bicycles-Bitterballen#2]
I discovered this accidentally while trying https://modrinth.com/mod/random-mob-effects.
It seems like a random zombie receives the potion effect and no check is done to see if it's a player. While the effect would do nothing on a Mob, it shouldn't outright crash the game.

Here's the crash log:
https://mclo.gs/OL0b93b

Cheers. My Dutch friend loves this mod by the way.

**Comment by electricsteve** [comment]
seems to be fixed in new version, but github isn't updated, only modrinth.
