### ISSUE TITLE
Game crashes when there is no blaze burner below frying setup.(1.20.1-0.0.85)

### ISSUE THREAD

**Issue by geesl** [pyzpre/Create-Bicycles-Bitterballen#6]
As the title above suggests, if a blaze burner is not placed beneath the basin when creating a frying station, the game will crash with a ticking block entity.
These are all the logs it produces.
[crash-2024-06-15_15.18.52-client.txt](https://github.com/user-attachments/files/15847755/crash-2024-06-15_15.18.52-client.txt)
[crash-2024-06-15_15.18.37-server.txt](https://github.com/user-attachments/files/15847761/crash-2024-06-15_15.18.37-server.txt)
[latest.log](https://github.com/user-attachments/files/15847762/latest.log)

**Comment by pyzpre** [comment]
Fixed in the latest version :)
